### PR TITLE
Add address property to box

### PR DESCRIPTION
**Pull request by gralin**
We need this for device configuration URL feature that was added in latest version of HA

### CODE REVIEW

**Comment by gralin** [comment]
@bbx-jp any chance you could check this PR? 👀

**Comment by kubawolanin** [comment]
@bbx-jp would you mind taking a look at this PR from @gralin?

I've already submitted a PR to HomeAssistant repo to have it implemented once this change is published:
https://github.com/home-assistant/core/pull/63396

(and previously mistakenly implemented https://github.com/blebox/blebox_uniapi/pull/131 since didn't notice this PR).

**Comment by gralin** [comment]
@kubawolanin I wanted to open that PR in HomeAssistant long time ago, right after configuration URL came out. But I knew it wouldn't get accepted if I used private variables (and now, so do you 😅). Since then I'm waiting for this simple PR to get merged. I emailed Blebox guys several times, but nothing. Only got one reply from technical support, that they want to look into this in 2022.

**Comment by dgtal1** [comment]
@kubawolanin, @gralin - looks like recently you're the active contributors to this project. It seems that BleBox doesn't give a damn about this API library anymore. They even stopped adding support for their new devices to this API. This significantly slows down the HA integration development. Even though I relize it's not ideal - in this situation I propose to fork this repo and build a separate PyPi library on it, then update the HA integration to use it. This assumes that you're gonna stay comited to the development of this new fork. Otherwise you may be waiting weeks or months (or forever) for your changes to be picked up by the BleBox devs. Due date of "2022" sounds so general that it may also never happen. The last time a PR was merged was 6 months ago...It's a big shame that this company first published an open source library and contributed in the Home Assistant repo to have an integration for their devices and now they stopped maintaining this. I understand they may not be interested in supporting the work on HA integration, but I don't understand why they simply don't care about their Python library, which may be used by many other projects. As usual integration with open smarthome systems is not a priority.

**Comment by dgtal1** [comment]
I personally don't have any hardware from BleBox (altought I'd like to try some - this kind of 'purchase' as yours sounds tempting😁). I'm helping a colleague (@shibby20)  who does have some stuff from them to integrate new devices they released months ago and never added to this library. I analyzed the HA integration for him and found out it barely requires any attention because support for new device types is made on the library level and that's how I came across to this repo. 

For now to handle the new features HA added (device URL) and new devices BleBox released maybe it'll be better to retrofit all the new PRs from this repo to a fork, then fork the HA integration and maintain it altogether as custom component until BleBox gets their sh*t together and start maintaining this repo again. They can easily retrofit all the code from these forks to the official repo at some point. Swicthing from a custom component to the version bundled together with HA should be completely transparent and painless I guess.

If I had some hardware from them perhaps I'd go there personally. They seem to have some nice sales specialists 🙃 (https://blebox.eu/kontakt/)

**Comment by gralin** [comment]
@dgtal1 if you would like to test BleBox hardware I can lend you something, I have some spare ones I only use from time to time. As for creating a custom component, I don't think people would have much motivation to develop it, knowing that there is an 'official' integration and your contributions could be more visible. I was happy when I could move away from using it as custom component and it would suck if I had to come back to it. I'm fine with using HACS and integrations that can't be made 'official' (e.g. becuase they are based on reversed engineering) but I see it as a bit inferior.

Btw, @kubawolanin, I noticed on BleBox website @dgtal1 linked, that one of the sales specialists is Adam Wolanin. Is that any family member of yours by any chance 😄

**Comment by kubawolanin** [comment]
> Btw, @kubawolanin, I noticed on BleBox website @dgtal1 linked, that one of the sales specialists is Adam Wolanin. Is that any family member of yours by any chance 😄

Nope, coincidence ;-)

**Comment by gralin** [comment]
@riokuu here is the PR to expose the address as property. After this is merged and released you can revive the old PR in HA (https://github.com/home-assistant/core/pull/63396) to use it for `configuration_url`.

PS. @kubawolanin, @dgtal1, BleBox nowa has a new developer working on this library and HA integration so we don't need to fork anything 🎉

**Pull request merged**
